spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduate2?useUnicode=true&characterEncoding=UTF-8&&useSSL=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

###################################### MyBatis 配置######################################
mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.example.graduate_sever.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
